name: "LLM Log Analyzer"
description: "Analyzes pipeline logs using a locally hosted LLM model"
author: "Rahul G S"

inputs:
  llm_script_path:
    description: "Path to the Python script for log analysis"
    required: false
    default: "C:/rahul/llm/llm-test.py"
  logs_pattern:
    description: "Glob pattern for logs to include"
    required: false
    default: "*.log"

runs:
  using: "composite"
  steps:
    - name: Combine Logs
      shell: pwsh
      run: |
        Write-Host "Searching for logs matching pattern: *.log"
        $logs = Get-ChildItem -Path . -Filter "*.log" -Recurse
        if ($logs.Count -eq 0) {
          Write-Host "No log files found."
        } else {
          New-Item -ItemType Directory -Force -Path combined_logs | Out-Null
          Get-Content $logs.FullName | Out-File -FilePath combined_logs/full_pipeline.log -Encoding utf8
          Write-Host "Combined log saved to combined_logs/full_pipeline.log"
        }

    - name: Run Local LLM Analyzer
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        Write-Host "Running local LLM analyzer..."
        python "${{ inputs.llm_script_path }}" combined_logs/full_pipeline.log > combined_logs/llm_output.json
        Write-Host "LLM Analysis Result:"
        Get-Content combined_logs/llm_output.json
