name: "LLM Log Analyzer"
description: "Analyzes pipeline logs using a locally hosted LLM model"
author: "Rahul G S"

inputs:
  llm_script_path:
    description: "Path to the Python script for log analysis"
    required: false
    default: "C:/rahul/llm/llm-test.py"
  logs_pattern:
    description: "Glob pattern for logs to include"
    required: false
    default: "*.log"

runs:
  using: "composite"
  steps:
    - name: Combine Logs
      shell: powershell
      run: |
        Write-Host "Searching for logs matching pattern: ${{ inputs.logs_pattern }}"
        $logs = Get-ChildItem -Path $PWD -Filter "${{ inputs.logs_pattern }}" -Recurse -ErrorAction SilentlyContinue
        if ($logs.Count -eq 0) {
          Write-Host "No log files found."
          exit 0
        } else {
          $combinedDir = Join-Path $PWD "combined_logs"
          New-Item -ItemType Directory -Force -Path $combinedDir | Out-Null
          $logs | ForEach-Object { Get-Content $_.FullName } | Out-File -FilePath (Join-Path $combinedDir "full_pipeline.log") -Encoding utf8
          Write-Host "Combined log saved to combined_logs/full_pipeline.log"
        }


    - name: Run Local LLM Analyzer
      shell: powershell
      run: |
        try {
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          Write-Host "Running local LLM analyzer..."
          python "${{ inputs.llm_script_path }}" combined_logs/full_pipeline.log > combined_logs/llm_output.json 2>&1
          Write-Host "LLM Analysis Result:"
          Get-Content combined_logs/llm_output.json
        } catch {
          Write-Host "LLM Analyzer failed: $($_.Exception.Message)"
          exit 1
        }
